name: On Push Clippy and Test

on: 
  push:
    paths:
      - src/**
      - migrations/**
      - .sqlx/**
      - static/**
      - Cargo.toml
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  SQLX_OFFLINE: true

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy --all-targets --all-features
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
