name: On Tag Build and Release
on:
  push:
    tags:
      - "v*.*.*"
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  SQLX_OFFLINE: true
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: cargo test --release --verbose
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/magnetite-cms
